package dynamoAddLambda;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.util.*;

@DynamoDBTable(tableName = "tasks")
public class Task {

    private String id;
    private String title;
    private String description;
    private String assignee;
    private String status;
    private String imgUrl;

    private ArrayList<HistoryItem> history;


    public Task() {}

    public Task(String title, String description) {
        this.title = title;
        this.description = description;
        this.status = "available";
        this.history= new ArrayList<>();
    }

    public Task(String title, String description, String assignee) {
        this.title = title;
        this.description = description;
        this.assignee = assignee;
        this.status = "assigned";
        this.history= new ArrayList<>();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    @DynamoDBAttribute
    public ArrayList<HistoryItem> getHistory() {
        return history;
    }

    public void setHistory(ArrayList<HistoryItem> history) {
        this.history = history;
    }

    public void addToHistory(HistoryItem historyItem){
        this.history.add(historyItem);
    }
    public String toString(){
        return "Title "+ this.title + " description: " + this.description + " assignee: " + this.assignee;
    }
}
