/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dynamoAddLambda;

import com.google.gson.JsonObject;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void save() {
//        JsonObject json = new JsonObject();
//        json.addProperty("title","test title");
//        json.addProperty("description","test desc");
//        json.addProperty("assignee","test assignee");
//        Library library = new Library();
//        library.save(json);
    }
}
